### ISSUE TITLE
Recommendation: Generalize what you can

### ISSUE THREAD

**Issue by melissamcewen** [dstewart97/f1-3-c2p1-colmar-academy#4]
When dealing with CSS I try to think about what things have in common and then make rules that apply to them. That way I can get general consistency and clearer/simpler code. So I look at different parts of the page and I'm like "hmm what can I share between these things." Like I did a large site for a major beverage company and divided all the different parts into different components like 
* image with text
* large image
* slider

and even though they all looked different (like there were 4 large images with different content), they contained similar patterns

Here for example is the "solution code" that creates a universal component called "Content Image Box"

```css
/* Universal Component - Content Image Box */

.content-image-box {
  display: flex;
  padding: 1rem 0 1rem 1rem;
  border-bottom: 1px solid rgb(245, 245, 245);
}

.content-image-box:first-child {
  padding-top: 0;
}

.content-image-box:last-child {
  padding-bottom: 0;
  border-bottom: none;
}

.content-image-box .media-container {
  width: 35%;
}

.content-image-box .text-content {
  display: flex;
  flex-direction: column;
  justify-content: center;
  width: 65%;
  padding: 0 0.75rem 0 1rem;
}

.content-image-box h4 {
  padding-bottom: .5rem;
  font-size: 1.25rem;
  font-weight: bold;
}

.content-image-box p {
  padding-bottom: .5rem;
}

.content-image-box .mobile {
  display: none;
}


@media only screen and (max-width: 895px) {
  .content-image-box .desktop {
    display: none;
  }

  .content-image-box .mobile {
    display: block;
  }

  .content-image-box {
    padding-left: 0;
    border-bottom: none;
  }

  .content-image-box .media-container {
    width: 100%;
  }
}
```

it's used in several sections
```html
 <!-- Information -->
  <div id="information-section" class="flex-content">
    <div class="main-content">
      <div class="media-container">
        <img src="resources/images/information-main.jpg">
      </div>
      <h3>It doesn't hurt to keep practicing</h3>
      <p>
        "I told my manager I wanted to learn design and shared ways it could be helpful in my current role. He responded right away, said, 'This is awesome,' and my company paid for the course."
      </p>
    </div>
    <div class="supporting-content">
      <div class="content-image-box">
        <div class="media-container">
          <img class="desktop" src="resources/images/information-orientation.jpg">
          <img class="mobile" src="resources/images/information-orientation-mobile.jpg">
        </div>
        <div class="text-content">
          <h4>Orientation date</h4>
          <p>Tue 10/11 & Wed 10/12: 8am - 3pm</p>
          <a href="#">Read more</a>
        </div>
      </div>
      <div class="content-image-box">
        <div class="media-container">
          <img class="desktop" src="resources/images/information-campus.jpg">
          <img class="mobile" src="resources/images/information-campus-mobile.jpg">
        </div>
        <div class="text-content">
          <h4>Our campus</h4>
          <p>Find which campus is close by you</p>
          <a href="#">Read more</a>
        </div>
      </div>
      <div class="content-image-box">
        <div class="media-container">
          <img class="desktop" src="resources/images/information-guest-lecture.jpg">
          <img class="mobile" src="resources/images/information-guest-lecture-mobile.jpg">
        </div>
        <div class="text-content">
          <h4>Our guest lecture</h4>
          <p>Join a keynote with Oliver Sack about music in medical treatment</p>
          <a href="#">Read more</a>
        </div>
      </div>
    </div>
  </div>

```

and
```html
  <!-- Thesis -->
  <div id="thesis-section">
    <h2>Thesis exhibits</h2>
    <div class="flex-content">
      <div class="main-content">
        <div class="media-container">
          <video src="resources/videos/thesis.mp4" controls>
            Video could not be loaded.
          </video>
        </div>
        <h3>Reimagine urban transportation</h3>
        <p>
          "Curabitur vitae libero in ipsum portitor consequat. Aliquam et commodo lectus, nec consequat neque. Sed non accumsan urna. Phasellus sed consequat ex. Etiam eget magna laoreet, effcitur dolor consequat, tristque ligula."
        </p>
      </div>
      <div class="supporting-content">
        <div class="content-image-box">
          <div class="media-container">
            <img src="resources/images/thesis-fisma.jpg">
          </div>
          <div class="text-content">
            <h4>Fisma: Design and Prototype</h4>
            <p>Designer showcase of new prototype product</p>
          </div>
        </div>
        <div class="content-image-box">
          <div class="media-container">
            <img src="resources/images/thesis-now-and-then.jpg">
          </div>
          <div class="text-content">
            <h4>Now and then</h4>
            <p>Research study about New York</p>
          </div>
        </div>
      </div>
    </div>
  </div>
```
